import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './fonts.css'
import LoginPage from './pages/Customer/LoginPage/LoginPage'
import { BrowserRouter, Route, Routes, Navigate } from 'react-router-dom'
import HomePage from './pages/Customer/HomePage/HomePage'
import SignUpPage from './pages/Customer/SignUpPage/SignupPage'
import ProductDetailPage from './pages/Customer/ProductDetail/ProductDetail'
import Trending from './pages/Customer/HomePage/HomePageDetails/Trending'
import Indies from './pages/Customer/HomePage/HomePageDetails/Indies'
import ActionFooter from './pages/Customer/HomePage/HomePageDetails/ActionFooter'
import Categories from './pages/Customer/HomePage/HomePageDetails/Categories'
import Comment from './pages/Customer/HomePage/HomePageDetails/Comment'
import Content from './pages/Customer/HomePage/HomePageDetails/Content'
import FAQs from './pages/Customer/HomePage/HomePageDetails/FAQs'
import Information from './pages/Customer/HomePage/HomePageDetails/Information'
import TopBanner from './pages/Customer/HomePage/HomePageDetails/TopBanner'
import Review from './pages/Customer/HomePage/HomePageDetails/Review'
import Newss from './pages/Customer/HomePage/HomePageDetails/News'
import ProductCartPage from './pages/Customer/CartPage/ProductCart/ProductCartPage'
import SummaryPayment from './components/Customer/CartPage/PaymentPage/SummaryPayment'
import SelectBankPage from './pages/Customer/CartPage/PaymentPage/SelectBankPage/SelectBankPage'
import FillPayment from './pages/Customer/CartPage/PaymentPage/PaymentPage/FillPayment'
import ConfirmPayment from './pages/Customer/CartPage/PaymentPage/ConfirmPayment/ConfirmPayment'
import GameActivationPage from './pages/Customer/CartPage/GameActivationPage/GameActivationPage'
import UserPage from './components/Customer/UserPage/UserPage'
import MyOrdersPage from './pages/Customer/UserPage/MyOrdersPage/MyOrdersPage'
import MyReviewsPage from './pages/Customer/UserPage/MyReviewsPage/MyReviewsPage'
import SettingsPage from './components/Customer/UserPage/SettingsPage/SettingsPage'
import SecurityPage from './pages/Customer/UserPage/SettingsPage/SecurityPage/SecurityPage'
import AvatarPage from './pages/Customer/UserPage/SettingsPage/AvatarPage/AvatarPage'
import GlobalAlert from './components/GlobalAlert'
import CheckPayment from './pages/Customer/CartPage/PaymentPage/CheckPayment/CheckPayment'
import PaymentFailure from './pages/Customer/CartPage/PaymentPage/PaymentStatus/PaymentFailure'
import SelectMethod from './pages/Customer/CartPage/PaymentPage/PaymentMethod/SelectMethod'
import GamePlatformPCPage from './pages/Customer/GamePlatformPage/GamePlatformPCPage'
import GamePlatformPlayStationPage from './pages/Customer/GamePlatformPage/GamePlatformPlayStationPage'
import GamePlatformXboxPage from './pages/Customer/GamePlatformPage/GamePlatformXboxPage'
import GamePlatformNintendoPage from './pages/Customer/GamePlatformPage/GamePlatformNintendoPage'
import App from './App'
// import App from './App.jsx'

createRoot(document.getElementById('root')).render(
  // <StrictMode>
    <App />
  // </StrictMode>,
)
